CMAES WIP

diff --git a/cudampilib/compile b/cudampilib/compile
--- a/cudampilib/compile
+++ b/cudampilib/compile
@@ -13,13 +13,30 @@ MONTECARLO_DIR="montecarlo"
 
 GENERIC_FLAGS="-I/usr/local/cuda-13.0/targets/x86_64-linux/include -Iinclude -L/usr/local/cuda-13.0/targets/x86_64-linux/lib -lcudart -lstdc++ -lm -Wl,-l:libnvidia-ml.so.1"
 
+# Locate c-cmaes sources (prefer sibling dir, fallback to absolute path suggested)
+CCMAES_DIR="../c-cmaes/src"
+if [ ! -d "$CCMAES_DIR" ]; then
+  if [ -d "$HOME/parallel-processing-cpu-and-gpu-env-and-lib-with-powercap/c-cmaes/src" ]; then
+    CCMAES_DIR="$HOME/parallel-processing-cpu-and-gpu-env-and-lib-with-powercap/c-cmaes/src"
+  fi
+fi
+if [ ! -d "$CCMAES_DIR" ]; then
+  echo "Error: c-cmaes sources not found. Expected in ../c-cmaes/src or \$HOME/parallel-processing-cpu-and-gpu-env-and-lib-with-powercap/c-cmaes/src"
+  exit 1
+fi
+
 mkdir -p $BUILD_DIR
 
-mpicc -fopenmp -c cudampicommon.c -I/usr/local/cuda-13.0/targets/x86_64-linux/include -Iinclude -o $BUILD_DIR/cudampicommon.o
-mpicc -fopenmp -c cudampilib.c -I/usr/local/cuda-13.0/targets/x86_64-linux/include -Iinclude -o $BUILD_DIR/cudampilib.o
-mpicc -fopenmp -c cudampi_state.c -I/usr/local/cuda-13.0/targets/x86_64-linux/include -Iinclude -o $BUILD_DIR/cudampi_state.o
-mpicc -fopenmp -c powercap_config.c -I/usr/local/cuda-13.0/targets/x86_64-linux/include -Iinclude -o $BUILD_DIR/powercap_config.o
-mpicc -fopenmp -c powercap.c -I/usr/local/cuda-13.0/targets/x86_64-linux/include -Iinclude -o $BUILD_DIR/powercap.o
+CC_INC_COMMON="-I/usr/local/cuda-13.0/targets/x86_64-linux/include -Iinclude -I$CCMAES_DIR"
+mpicc -fopenmp -c cudampicommon.c $CC_INC_COMMON -o $BUILD_DIR/cudampicommon.o
+mpicc -fopenmp -c cudampilib.c $CC_INC_COMMON -o $BUILD_DIR/cudampilib.o
+mpicc -fopenmp -c cudampi_state.c $CC_INC_COMMON -o $BUILD_DIR/cudampi_state.o
+mpicc -fopenmp -c powercap_config.c $CC_INC_COMMON -o $BUILD_DIR/powercap_config.o
+mpicc -fopenmp -c powercap.c $CC_INC_COMMON -o $BUILD_DIR/powercap.o
+
+# c-cmaes core
+mpicc -fopenmp -c $CCMAES_DIR/cmaes.c -I$CCMAES_DIR -o $BUILD_DIR/cmaes.o
+mpicc -fopenmp -c $CCMAES_DIR/boundary_transformation.c -I$CCMAES_DIR -o $BUILD_DIR/boundary_transformation.o
 
 #nvcc -c $APPS_DIR/$APP_DIR/appkernel.cu -o $BUILD_DIR/appkernel.o
 nvcc -c $APPS_DIR/$VECMAXDIV_DIR/appkernelvecmaxdiv.cu -o $BUILD_DIR/appkernelvecmaxdiv.o -Iinclude
@@ -41,22 +58,23 @@ mpicc -fopenmp -O3 -march=native -ffast-math -funroll-loops -c $APPS_DIR/$MONTEC
 
 
 #mpicc -fopenmp -o $BUILD_DIR/cudampislave cudampislave.c $BUILD_DIR/appkernel.o $BUILD_DIR/cudampicommon.o -I/usr/local/cuda-13.0/targets/x86_64-linux/include -Iinclude -L/usr/local/cuda-13.0/targets/x86_64-linux/lib -lcudart -lstdc++
-mpicc -fopenmp -o $BUILD_DIR/cudampislave-vecmaxdiv cudampislave.c $BUILD_DIR/cpukernelvecmaxdiv.o $BUILD_DIR/appkernelvecmaxdiv.o $BUILD_DIR/cudampicommon.o $GENERIC_FLAGS
-mpicc -fopenmp -o $BUILD_DIR/cudampislave-vecadd cudampislave.c $BUILD_DIR/cpukernelvecadd.o $BUILD_DIR/appkernelvecadd.o $BUILD_DIR/cudampicommon.o $GENERIC_FLAGS
-mpicc -fopenmp -o $BUILD_DIR/cudampislave-collatz cudampislave.c $BUILD_DIR/cpukernelcollatz.o $BUILD_DIR/appkernelcollatz.o $BUILD_DIR/cudampicommon.o $GENERIC_FLAGS
-mpicc -fopenmp -o $BUILD_DIR/cudampislave-patternsearch cudampislave.c $BUILD_DIR/cpukernelpatternsearch.o $BUILD_DIR/appkernelpatternsearch.o $BUILD_DIR/cudampicommon.o $GENERIC_FLAGS
-mpicc -fopenmp -o $BUILD_DIR/cudampislave-twinprime cudampislave.c $BUILD_DIR/cpukerneltwinprime.o $BUILD_DIR/appkerneltwinprime.o $BUILD_DIR/cudampicommon.o $GENERIC_FLAGS
-mpicc -fopenmp -o $BUILD_DIR/cudampislave-rnn cudampislave.c $BUILD_DIR/cpukernelrnn.o $BUILD_DIR/appkernelrnn.o $BUILD_DIR/cudampicommon.o $GENERIC_FLAGS -lcublas -I/opt/intel/oneapi/mkl/latest/include -L/opt/intel/oneapi/mkl/latest/lib/intel64 -Wl,-Bstatic -lmkl_intel_lp64 -lmkl_gnu_thread -lmkl_core -Wl,-Bdynamic -lpthread -lm
-mpicc -fopenmp -o $BUILD_DIR/cudampislave-montecarlo cudampislave.c $BUILD_DIR/cpukernelmontecarlo.o $BUILD_DIR/appkernelmontecarlo.o $BUILD_DIR/cudampicommon.o $GENERIC_FLAGS
+mpicc -fopenmp -o $BUILD_DIR/cudampislave-vecmaxdiv cudampislave.c $BUILD_DIR/cpukernelvecmaxdiv.o $BUILD_DIR/appkernelvecmaxdiv.o $BUILD_DIR/cudampicommon.o $CC_INC_COMMON $GENERIC_FLAGS
+mpicc -fopenmp -o $BUILD_DIR/cudampislave-vecadd cudampislave.c $BUILD_DIR/cpukernelvecadd.o $BUILD_DIR/appkernelvecadd.o $BUILD_DIR/cudampicommon.o $CC_INC_COMMON $GENERIC_FLAGS
+mpicc -fopenmp -o $BUILD_DIR/cudampislave-collatz cudampislave.c $BUILD_DIR/cpukernelcollatz.o $BUILD_DIR/appkernelcollatz.o $BUILD_DIR/cudampicommon.o $CC_INC_COMMON $GENERIC_FLAGS
+mpicc -fopenmp -o $BUILD_DIR/cudampislave-patternsearch cudampislave.c $BUILD_DIR/cpukernelpatternsearch.o $BUILD_DIR/appkernelpatternsearch.o $BUILD_DIR/cudampicommon.o $CC_INC_COMMON $GENERIC_FLAGS
+mpicc -fopenmp -o $BUILD_DIR/cudampislave-twinprime cudampislave.c $BUILD_DIR/cpukerneltwinprime.o $BUILD_DIR/appkerneltwinprime.o $BUILD_DIR/cudampicommon.o $CC_INC_COMMON $GENERIC_FLAGS
+mpicc -fopenmp -o $BUILD_DIR/cudampislave-rnn cudampislave.c $BUILD_DIR/cpukernelrnn.o $BUILD_DIR/appkernelrnn.o $BUILD_DIR/cudampicommon.o $CC_INC_COMMON $GENERIC_FLAGS -lcublas -I/opt/intel/oneapi/mkl/latest/include -L/opt/intel/oneapi/mkl/latest/lib/intel64 -Wl,-Bstatic -lmkl_intel_lp64 -lmkl_gnu_thread -lmkl_core -Wl,-Bdynamic -lpthread -lm
+mpicc -fopenmp -o $BUILD_DIR/cudampislave-montecarlo cudampislave.c $BUILD_DIR/cpukernelmontecarlo.o $BUILD_DIR/appkernelmontecarlo.o $BUILD_DIR/cudampicommon.o $CC_INC_COMMON $GENERIC_FLAGS
 
 #mpicc -fopenmp -o $BUILD_DIR/app $APPS_DIR/$APP_DIR/app.c $BUILD_DIR/appkernel.o $BUILD_DIR/cudampilib.o $BUILD_DIR/cudampicommon.o -I/usr/local/cuda-13.0/targets/x86_64-linux/include -Iinclude -L/usr/local/cuda-13.0/targets/x86_64-linux/lib -lcudart -lstdc++
-mpicc -fopenmp -o $BUILD_DIR/app-streams-vecmaxdiv $APPS_DIR/$VECMAXDIV_DIR/app-streams-vecmaxdiv.c $BUILD_DIR/cpukernelvecmaxdiv.o $BUILD_DIR/appkernelvecmaxdiv.o $BUILD_DIR/cudampilib.o $BUILD_DIR/cudampicommon.o $BUILD_DIR/powercap_config.o $BUILD_DIR/powercap.o $BUILD_DIR/cudampi_state.o $GENERIC_FLAGS
-mpicc -fopenmp -o $BUILD_DIR/app-streams-vecadd $APPS_DIR/$VECADD_DIR/app-streams-vecadd.c $BUILD_DIR/cpukernelvecadd.o $BUILD_DIR/appkernelvecadd.o $BUILD_DIR/cudampilib.o $BUILD_DIR/cudampicommon.o $BUILD_DIR/powercap_config.o $BUILD_DIR/powercap.o $BUILD_DIR/cudampi_state.o $GENERIC_FLAGS
-mpicc -fopenmp -o $BUILD_DIR/app-streams-collatz $APPS_DIR/$COLLATZ_DIR/app-streams-collatz.c $BUILD_DIR/cpukernelcollatz.o $BUILD_DIR/appkernelcollatz.o $BUILD_DIR/cudampilib.o $BUILD_DIR/cudampicommon.o $BUILD_DIR/powercap_config.o $BUILD_DIR/powercap.o $BUILD_DIR/cudampi_state.o $GENERIC_FLAGS
-mpicc -fopenmp -o $BUILD_DIR/app-streams-patternsearch $APPS_DIR/$PATTERNSEARCH_DIR/app-streams-patternsearch.c $BUILD_DIR/cpukernelpatternsearch.o $BUILD_DIR/appkernelpatternsearch.o $BUILD_DIR/cudampilib.o $BUILD_DIR/cudampicommon.o $BUILD_DIR/powercap_config.o $BUILD_DIR/powercap.o $BUILD_DIR/cudampi_state.o $GENERIC_FLAGS
-mpicc -fopenmp -o $BUILD_DIR/app-streams-twinprime $APPS_DIR/$TWINPRIME_DIR/app-streams-twinprime.c $BUILD_DIR/cpukerneltwinprime.o $BUILD_DIR/appkerneltwinprime.o $BUILD_DIR/cudampilib.o $BUILD_DIR/cudampicommon.o $BUILD_DIR/powercap_config.o $BUILD_DIR/powercap.o $BUILD_DIR/cudampi_state.o $GENERIC_FLAGS
-mpicc -fopenmp -o $BUILD_DIR/app-streams-rnn $APPS_DIR/$RNN_DIR/app-streams-rnn.c $BUILD_DIR/cpukernelrnn.o $BUILD_DIR/appkernelrnn.o $BUILD_DIR/cudampilib.o $BUILD_DIR/cudampicommon.o $BUILD_DIR/powercap_config.o $BUILD_DIR/powercap.o $BUILD_DIR/cudampi_state.o $GENERIC_FLAGS -lcublas -I/opt/intel/oneapi/mkl/latest/include -L/opt/intel/oneapi/mkl/latest/lib/intel64 -Wl,-Bstatic -lmkl_intel_lp64 -lmkl_gnu_thread -lmkl_core -Wl,-Bdynamic -lpthread -lm
-mpicc -fopenmp -o $BUILD_DIR/app-streams-montecarlo $APPS_DIR/$MONTECARLO_DIR/app-streams-montecarlo.c $BUILD_DIR/cpukernelmontecarlo.o $BUILD_DIR/appkernelmontecarlo.o $BUILD_DIR/cudampilib.o $BUILD_DIR/cudampicommon.o $BUILD_DIR/powercap_config.o $BUILD_DIR/powercap.o $BUILD_DIR/cudampi_state.o $GENERIC_FLAGS
+LINK_CMAES="$BUILD_DIR/cmaes.o $BUILD_DIR/boundary_transformation.o"
+mpicc -fopenmp -o $BUILD_DIR/app-streams-vecmaxdiv $APPS_DIR/$VECMAXDIV_DIR/app-streams-vecmaxdiv.c $BUILD_DIR/cpukernelvecmaxdiv.o $BUILD_DIR/appkernelvecmaxdiv.o $BUILD_DIR/cudampilib.o $BUILD_DIR/cudampicommon.o $BUILD_DIR/powercap_config.o $BUILD_DIR/powercap.o $BUILD_DIR/cudampi_state.o $LINK_CMAES $CC_INC_COMMON $GENERIC_FLAGS
+mpicc -fopenmp -o $BUILD_DIR/app-streams-vecadd $APPS_DIR/$VECADD_DIR/app-streams-vecadd.c $BUILD_DIR/cpukernelvecadd.o $BUILD_DIR/appkernelvecadd.o $BUILD_DIR/cudampilib.o $BUILD_DIR/cudampicommon.o $BUILD_DIR/powercap_config.o $BUILD_DIR/powercap.o $BUILD_DIR/cudampi_state.o $LINK_CMAES $CC_INC_COMMON $GENERIC_FLAGS
+mpicc -fopenmp -o $BUILD_DIR/app-streams-collatz $APPS_DIR/$COLLATZ_DIR/app-streams-collatz.c $BUILD_DIR/cpukernelcollatz.o $BUILD_DIR/appkernelcollatz.o $BUILD_DIR/cudampilib.o $BUILD_DIR/cudampicommon.o $BUILD_DIR/powercap_config.o $BUILD_DIR/powercap.o $BUILD_DIR/cudampi_state.o $LINK_CMAES $CC_INC_COMMON $GENERIC_FLAGS
+mpicc -fopenmp -o $BUILD_DIR/app-streams-patternsearch $APPS_DIR/$PATTERNSEARCH_DIR/app-streams-patternsearch.c $BUILD_DIR/cpukernelpatternsearch.o $BUILD_DIR/appkernelpatternsearch.o $BUILD_DIR/cudampilib.o $BUILD_DIR/cudampicommon.o $BUILD_DIR/powercap_config.o $BUILD_DIR/powercap.o $BUILD_DIR/cudampi_state.o $LINK_CMAES $CC_INC_COMMON $GENERIC_FLAGS
+mpicc -fopenmp -o $BUILD_DIR/app-streams-twinprime $APPS_DIR/$TWINPRIME_DIR/app-streams-twinprime.c $BUILD_DIR/cpukerneltwinprime.o $BUILD_DIR/appkerneltwinprime.o $BUILD_DIR/cudampilib.o $BUILD_DIR/cudampicommon.o $BUILD_DIR/powercap_config.o $BUILD_DIR/powercap.o $BUILD_DIR/cudampi_state.o $LINK_CMAES $CC_INC_COMMON $GENERIC_FLAGS
+mpicc -fopenmp -o $BUILD_DIR/app-streams-rnn $APPS_DIR/$RNN_DIR/app-streams-rnn.c $BUILD_DIR/cpukernelrnn.o $BUILD_DIR/appkernelrnn.o $BUILD_DIR/cudampilib.o $BUILD_DIR/cudampicommon.o $BUILD_DIR/powercap_config.o $BUILD_DIR/powercap.o $BUILD_DIR/cudampi_state.o $LINK_CMAES $CC_INC_COMMON $GENERIC_FLAGS -lcublas -I/opt/intel/oneapi/mkl/latest/include -L/opt/intel/oneapi/mkl/latest/lib/intel64 -Wl,-Bstatic -lmkl_intel_lp64 -lmkl_gnu_thread -lmkl_core -Wl,-Bdynamic -lpthread -lm
+mpicc -fopenmp -o $BUILD_DIR/app-streams-montecarlo $APPS_DIR/$MONTECARLO_DIR/app-streams-montecarlo.c $BUILD_DIR/cpukernelmontecarlo.o $BUILD_DIR/appkernelmontecarlo.o $BUILD_DIR/cudampilib.o $BUILD_DIR/cudampicommon.o $BUILD_DIR/powercap_config.o $BUILD_DIR/powercap.o $BUILD_DIR/cudampi_state.o $LINK_CMAES $CC_INC_COMMON $GENERIC_FLAGS
 
 
 echo "Build complete. Executables and object files are in '$BUILD_DIR'."
